# Конфигурация обработки HTML
remove_tags:           # Удаляемые HTML-теги
  - script
  - style
  - footer
max_html_length: 10000000 # Макс. длина обрабатываемого HTML

# Поля для извлечения
fields:
  title:               # Название поля
    selectors:         # Последовательность селекторов
      - type: css      # Тип селектора (css/xpath)
        selector: '#page-title'  # CSS/XPath выражение
        strategy: first  # Стратегия: first/multi
        extract: text  # Извлекать: text/attr
        post_process:  # Постобработка:
          - strip      # Удаление пробелов
          #- unescape   # HTML-декодирование
        # validate:      # Валидация:
        #   - required   # Обязательное поле
        #   - max_length: 300  # Макс. длина
        # bio_scope: element
      - type: xpath
        selector: '//meta[@name="citation_title"]'
        extract: attr
        attr_name: content
        # bio_scope: element

  author:
    selectors:
      - type: css
        selector: 'meta[name="citation_author"]'
        strategy: multi
        extract: attr
        attr_name: content
        post_process:
          - strip
      - type: css
        selector: 'meta[name="DC.Contributor"]'
        strategy: multi
        extract: attr
        attr_name: content
        post_process:
          - strip
      - type: css
        selector: '.contributor-list .contributor .name'
        strategy: multi
        extract: innerText
        post_process:
          - strip

  date:
    selectors:
      - type: css
        selector: 'meta[name="citation_publication_date"]'  # Регулярное выражение
        extract: attr
        attr_name: content
        #regex: '(\d{4}-\d{2}-\d{2})'   # Извлечение части
        # post_process:
        #   - normalize_date  # Нормализация даты
        # validate:
        #   - date
        # bio_scope: element
      - type: css
        selector: '.highwire-cite-published-year'  # Регулярное выражение
        strategy: first
        extract: text
        regex: '(\d{4})'   # Извлечение части
        # post_process:
        #   - normalize_date  # Нормализация даты
        # validate:
        #   - date
        # bio_scope: element
      - type: css
        selector: 'meta[name="DC.Date"]'  # Регулярное выражение
        extract: attr
        attr_name: content
        #regex: '(\d{4}-\d{2}-\d{2})'   # Извлечение части
        # post_process:
        #   - normalize_date  # Нормализация даты
        # validate:
        #   - date
        # bio_scope: element
  doi:
    selectors:
      - type: css
        selector: 'meta[name="citation_doi"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip
      - type: css
        selector: '.highwire-cite-doi a'
        strategy: first
        extract: text
        post_process:
          - strip
        regex: 'https?://doi\.org/10\.\S+'

  issn:
    selectors:
      - type: css
        selector: 'meta[name="citation_issn"]'
        strategy: multi
        extract: attr
        attr_name: content
        post_process:
          - strip

  journal:
    selectors:
      - type: css
        selector: 'meta[name="citation_journal_title"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip
      - type: css
        selector: '.highwire-cite-journal'
        strategy: first
        extract: text
        post_process:
          - strip

  publisher:
    selectors:
      - type: css
        selector: 'meta[name="citation_publisher"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip
      - type: css
        selector: 'meta[name="DC.Publisher"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  first_page:
    selectors:
      - type: css
        selector: 'meta[name="citation_firstpage"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  last_page:
    selectors:
      - type: css
        selector: 'meta[name="citation_lastpage"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  language:
    selectors:
      - type: css
        selector: 'meta[name="DC.Language"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  volume:
    selectors:
      - type: css
        selector: 'meta[name="citation_volume"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip
      - type: css
        selector: '.highwire-cite-volume-issue'
        strategy: first
        extract: text
        post_process:
          - strip

  issue:
    selectors:
      - type: css
        selector: 'meta[name="citation_issue"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  abstract:
    selectors:
      - type: css
        selector: 'meta[name="DC.Description"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip
      - type: css
        selector: '.article .abstract'
        strategy: first
        extract: innerText
        post_process:
          - strip

  affiliation:
    selectors:
      - type: css
        selector: 'meta[name="citation_author_institution"]'
        strategy: multi
        extract: attr
        attr_name: content
        post_process:
          - strip

  orcid:
    selectors:
      - type: xpath
        selector: "//div[contains(@class, 'contributor-list')]//div[contains(@class, 'name')]//a[contains(@href, 'orcid.org')]"
        strategy: multi
        extract: attr
        attr_name: href
        post_process:
          - strip
      - type: css
        selector: 'meta[name="citation_author_orcid"]'
        strategy: multi
        extract: attr
        attr_name: content
        post_process:
          - strip

# Пользовательские валидаторы
validators:
  max_length: '\S{1,120}'  # Регулярное выражение