# Конфигурация обработки HTML
remove_tags:           # Удаляемые HTML-теги
  - script
  - style
  - footer
max_html_length: 10000000 # Макс. длина обрабатываемого HTML

# Поля для извлечения
fields:
  title:               # Название поля
    selectors:         # Последовательность селекторов
      - type: css      # Тип селектора (css/xpath)
        selector: '#page-title'  # CSS/XPath выражение
        strategy: first  # Стратегия: first/multi
        extract: text  # Извлекать: text/attr
      - type: xpath
        selector: '//meta[@name="citation_title"]'
        extract: attr
        attr_name: content

  author:
    selectors:
      - type: css
        selector: 'meta[name="citation_author"]'
        strategy: multi
        extract: attr
        attr_name: content
      - type: css
        selector: 'meta[name="DC.Contributor"]'
        strategy: multi
        extract: attr
        attr_name: content
      - type: css
        selector: '.contributor-list .contributor .name'
        strategy: multi
        extract: innerText

  date:
    selectors:
      - type: css
        selector: 'meta[name="citation_publication_date"]'  # Регулярное выражение
        extract: attr
        attr_name: content
      - type: css
        selector: '.highwire-cite-published-year'  # Регулярное выражение
        strategy: first
        extract: text
        #regex: '(\d{4})'   # Извлечение части
      - type: css
        selector: 'meta[name="DC.Date"]'  # Регулярное выражение
        extract: attr
        attr_name: content

  doi:
    selectors:
      - type: css
        selector: 'meta[name="citation_doi"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: '.highwire-cite-doi a'
        strategy: first
        extract: text
        regex: 'https?://doi\.org/10\.\S+'

  issn:
    selectors:
      - type: css
        selector: 'meta[name="citation_issn"]'
        strategy: multi
        extract: attr
        attr_name: content

  journal:
    selectors:
      - type: css
        selector: 'meta[name="citation_journal_title"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: '.highwire-cite-journal'
        strategy: first
        extract: text

  publisher:
    selectors:
      - type: css
        selector: 'meta[name="citation_publisher"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: 'meta[name="DC.Publisher"]'
        strategy: first
        extract: attr
        attr_name: content

  first_page:
    selectors:
      - type: css
        selector: 'meta[name="citation_firstpage"]'
        strategy: first
        extract: attr
        attr_name: content

  last_page:
    selectors:
      - type: css
        selector: 'meta[name="citation_lastpage"]'
        strategy: first
        extract: attr
        attr_name: content

  language:
    selectors:
      - type: css
        selector: 'meta[name="DC.Language"]'
        strategy: first
        extract: attr
        attr_name: content

  volume:
    selectors:
      - type: css
        selector: 'meta[name="citation_volume"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: '.highwire-cite-volume-issue'
        strategy: first
        extract: text

  issue:
    selectors:
      - type: css
        selector: 'meta[name="citation_issue"]'
        strategy: first
        extract: attr
        attr_name: content

  abstract:
    selectors:
      - type: css
        selector: 'meta[name="DC.Description"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: '.article .abstract'
        strategy: first
        extract: innerText

  affiliation:
    selectors:
      - type: css
        selector: 'meta[name="citation_author_institution"]'
        strategy: multi
        extract: attr
        attr_name: content

  orcid:
    selectors:
      - type: xpath
        selector: "//div[contains(@class, 'contributor-list')]//div[contains(@class, 'name')]//a[contains(@href, 'orcid.org')]"
        strategy: multi
        extract: attr
        attr_name: href
      - type: css
        selector: 'meta[name="citation_author_orcid"]'
        strategy: multi
        extract: attr
        attr_name: content