# Конфигурация обработки HTML
remove_tags:
  - script
  - style
  - footer
  - noscript

fields:
  title:
    selectors:
      - type: css
        selector: '.publication-title'
        strategy: first
        extract: innerText
      - type: css
        selector: 'meta[name="citation_title"]'
        strategy: first
        extract: attr
        attr_name: content

  subtitle:
    selectors:
      - type: css
        selector: '.publication-sub-title'
        strategy: first
        extract: text

  date:
    selectors:
      - type: css
        selector: 'meta[name="dc.date"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: 'meta[name="citation_publication_date"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: 'meta[name="citation_online_date"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: '#wd-book-pub-date [itemprop="datePublished"]'
        strategy: first
        extract: text

  author:
    selectors:
      - type: css
        selector: '#wd-book-author span[itemprop="author"] [itemprop="name"]'
        strategy: multi
        extract: innerText
      - type: css
        selector: 'meta[name="citation_author"]'
        strategy: multi
        extract: attr
        attr_name: content

  editor:
    selectors:
      - type: css
        selector: '#wd-book-editor [itemprop="author"] [itemprop="name"]'
        strategy: multi
        extract: innerText

  orcid:
    selectors:
      - type: xpath
        selector: '//*[@itemprop="author"]//a[contains(@href, "orcid.org")]'
        strategy: multi
        extract: attr
        attr_name: href

  affiliation:
    selectors:
      - type: css
        selector: 'meta[name="citation_author_institution"]'
        strategy: multi
        extract: attr
        attr_name: content
      - type: css
        selector: '#wd-bk-auth-aff p'
        strategy: multi
        extract: text

  doi:
    selectors:
      - type: css
        selector: 'meta[name="citation_doi"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: '#wd-bk-pg-doi p'
        strategy: first
        extract: innerText

  issn:
    selectors:
      - type: css
        selector: 'meta[name="citation_issn"]'
        strategy: first
        extract: attr
        attr_name: content

  isbn:
    selectors:
      - type: css
        selector: '#wd-book-print-isbn'
        strategy: first
        extract: text
        regex: 'Print ISBN:\s*([0-9-]+)'

  eisbn:
    selectors:
      - type: css
        selector: '#wd-book-online-isbn'
        strategy: first
        extract: text
        regex: 'Online ISBN:\s*([0-9-]+)'
      - type: css
        selector: 'meta[name="citation_isbn"]'
        strategy: first
        extract: attr
        attr_name: content

  publisher:
    selectors:
      - type: css
        selector: 'meta[name="citation_publisher"]'
        strategy: first
        extract: attr
        attr_name: content

  pages:
    selectors:
      - type: css
        selector: '#wd-bk-pg-extent p'
        strategy: first
        extract: text

  language:
    selectors:
      - type: css
        selector: 'meta[name="citation_language"]'
        strategy: first
        extract: attr
        attr_name: content

  keyword:
    selectors:
      - type: css
        selector: '[class*="keyword"][class*="wd-jnl"] p'
        strategy: first
        extract: text

  abstract:
    selectors:
      - type: css
        selector: '#wd-book-page-intro'
        strategy: first
        extract: innerText
      - type: css
        selector: 'meta[name="citation_abstract"]'
        strategy: first
        extract: attr
        attr_name: content

  doc_type:
    selectors:
      - type: css
        selector: 'meta[name="asset_type"]'
        strategy: first
        extract: attr
        attr_name: content