# Конфигурация обработки HTML
remove_tags:
  - script
  - style
  - footer
  - noscript

fields:
  title:
    selectors:
      - type: xpath
        selector: '//meta[@name="citation_title"]'
        extract: attr
        attr_name: content
      - type: xpath
        selector: '//meta[@property="og:title"]'
        extract: attr
        attr_name: content
      - type: css
        selector: '.book-info__title'
        strategy: first
        extract: text
      - type: css
        selector: '#getCitation .citation-title'
        strategy: first
        extract: text

  subtitle:
    selectors:
      - type: css
        selector: '.book-info__title .subtitle'
        strategy: first
        extract: innerText
      - type: css
        selector: '#getCitation .citation-title .subtitle'
        strategy: first
        extract: text

  date:
    selectors:
      - type: css
        selector: 'meta[name="citation_publication_date"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: '.book-info__publication-date'
        strategy: multi
        extract: text
      - type: css
        selector: '#getCitation .citation-publication-date'
        strategy: first
        extract: innerText
        regex: '\d{4}'

  author:
    selectors:
      - type: css
        selector: 'meta[name="citation_author"]'
        strategy: multi
        extract: attr
        attr_name: content
      - type: css
        selector: '.book-info__authors .authors .al-author-name .linked-name'
        strategy: multi
        extract: innerText
      - type: css
        selector: '#getCitation .citation-author'
        strategy: multi
        extract: text

  editor:
    selectors:
      - type: css
        selector: '.book-info__authors .editors .al-author-name .linked-name'
        strategy: multi
        extract: text

  affiliation:
    selectors:
      - type: css
        selector: '.book-info__authors .info-card-affilitation .aff'
        strategy: multi
        extract: innerText

  doi:
    selectors:
      - type: css
        selector: 'meta[name="citation_doi"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: '.book-info__doi-link'
        strategy: first
        extract: text
      - type: css
        selector: '#getCitation .citation-doi'
        strategy: first
        extract: text

  eisbn:
    selectors:
      - type: xpath
        selector: "//div[contains(concat(' ', normalize-space(@class), ' '), ' book-info__isbn ')][div[@class='book-info__isbn-text'][contains(text(), 'lectronic')]]"
        strategy: multi
        extract: text
      - type: xpath
        selector: '//div[@id="getCitation"]/div[@class="citation-isbn"][span[contains(text(), "ISBN (electronic)")]]'
        strategy: multi
        extract: text

  isbn:
    selectors:
      - type: xpath
        selector: '//div[contains(concat(" ", normalize-space(@class), " "), " book-info__isbn ")][div[contains(concat(" ", normalize-space(@class), " "), " book-info__isbn-text ")][contains(text(), "ardback") or contains(text(), "aperback") or contains(text(), "rint")]]/div[contains(concat(" ", normalize-space(@class), " "), " book-info__isbn-number ")]'
        strategy: multi
        extract: text
      - type: xpath
        selector: '//div[@id="getCitation"]/div[@class="citation-isbn"][span[contains(text(), "ISBN (print)")]]'
        strategy: multi
        extract: text

  book_series:
    selectors:
      - type: css
        selector: '.book-series'
        strategy: first
        extract: innerText
      - type: xpath
        selector: '//div[contains(@class, "special-collections-wrap")]//div[contains(., "Book Series:")]/a'
        strategy: first
        extract: text
      
  volume:
    selectors:
      - type: css
        selector: '.book-info__volume-number'
        strategy: first
        extract: innerText

  publisher:
    selectors:
      - type: css
        selector: 'meta[name="citation_publisher"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: '.book-info__publisher-name'
        strategy: first
        extract: text
      - type: css
        selector: '#getCitation .citation-publisher'
        strategy: first
        extract: text

  pages:
    selectors:
      - type: css
        selector: '.book-info__pagecount-number'
        strategy: first
        extract: text

  doc_type:
    selectors:
      - type: css
        selector: 'meta[property="og:type"]'
        strategy: first
        extract: attr
        attr_name: content

  abstract:
    selectors:
      - type: css
        selector: '#book-info__abstract .abstract'
        strategy: first
        extract: innerText
      - type: css
        selector: 'meta[property="og:description"]'
        strategy: first
        extract: attr
        attr_name: content
      - type: css
        selector: 'meta[name="description"]'
        strategy: first
        extract: attr
        attr_name: content