# Конфигурация обработки HTML
remove_tags:           # Удаляемые HTML-теги
  - script
  - style
  - footer
  - noscript

# Поля для извлечения
fields:
  title:               # Название поля
    selectors:         # Последовательность селекторов
      - type: css      # Тип селектора (css/xpath)
        selector: '.title-wrap h1.wi-article-title'  # CSS/XPath выражение
        strategy: first  # Стратегия: first/multi
        extract: innerText  # Извлекать: text/attr/innerText
        post_process:  # Постобработка:
          - strip      # Удаление пробелов
          - unescape   # HTML-декодирование
        validate:      # Валидация:
         - required   # Обязательное поле
      - type: xpath
        selector: '//meta[@name="citation_title"]'
        extract: attr
        attr_name: content

  author:
    selectors:
      - type: css
        selector: 'meta[name="citation_author"]'
        strategy: multi
        extract: attr
        attr_name: content
        post_process:
          - strip
          - title

      - type: css
        selector: '.wi-authors .al-authors-list .al-author-name-more .linked-name'
        strategy: multi
        extract: innerText
        post_process:
          - strip
          - title

  date:
    selectors:
      - type: css
        selector: 'meta[name="citation_publication_date"]'  # Регулярное выражение
        extract: attr
        attr_name: content
        regex: '(\d{4}-\d{2}-\d{2})'   # Извлечение части
        post_process:
          - normalize_date  # Нормализация даты
        validate:
          - date

      - type: css
        selector: '.ww-citation-date-wrap .citation-date'  # Регулярное выражение
        strategy: first
        extract: text
        regex: '(\d{4})'   # Извлечение части
        post_process:
          - normalize_date  # Нормализация даты
        validate:
          - date

  doi:
    selectors:
      - type: css
        selector: 'meta[name="citation_doi"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

      - type: xpath
        selector: '//div[@class="ww-citation-primary"]/a[contains(text(), "doi.org/10.")]'
        strategy: first
        extract: text
        post_process:
          - strip

  issn:
    selectors:
      - type: css
        selector: 'meta[name="citation_issn"]'
        strategy: multi
        extract: attr
        attr_name: content
        regex: '\d{4}-\d{3}[\dXx]'
      - type: xpath
        selector: '//div[@class="journal-footer-colophon"]//li[contains(text(), "Print ISSN ")]'
        strategy: first
        extract: text
        regex: '\d{4}-\d{3}[\dXx]'

  eissn:
    selectors:
      - type: xpath
        selector: '//div[@class="journal-footer-colophon"]//li[contains(text(), "Online ISSN")]'
        strategy: first
        extract: text
        regex: '\d{4}-\d{3}[\dXx]'

  journal:
    selectors:
      - type: css
        selector: 'meta[name="citation_journal_title"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip
      - type: css
        selector: '.ww-citation-primary em'
        strategy: first
        extract: text
        post_process:
          - strip

  publisher:
    selectors:
      - type: css
        selector: 'meta[name="citation_publisher"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip
          - title

  first_page:
    selectors:
      - type: css
        selector: 'meta[name="citation_firstpage"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  last_page:
    selectors:
      - type: css
        selector: 'meta[name="citation_lastpage"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  language:
    selectors:
      - type: css
        selector: 'meta[name="citation_language"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  volume:
    selectors:
      - type: css
        selector: 'meta[name="citation_volume"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  issue:
    selectors:
      - type: css
        selector: 'meta[name="citation_issue"]'
        strategy: first
        extract: attr
        attr_name: content
        post_process:
          - strip

  abstract:
    selectors:
      - type: css
        selector: '#ContentTab .abstract'
        strategy: first
        extract: text
        post_process:
          - strip

  affiliation:
    selectors:
      - type: css
        selector: 'meta[name="citation_author_institution"]'
        strategy: multi
        extract: attr
        attr_name: content
        post_process:
          - strip

  doc_type:
    selectors:
      - type: css
        selector: '.journal-info__format-label'
        strategy: first
        extract: text
        post_process:
          - strip
  
  keyword:
    selectors:
      - type: css
        selector: 'meta[name="citation_keyword"]'
        strategy: multi
        extract: attr
        attr_name: content
        post_process:
          - strip

# Пользовательские валидаторы
validators:
  max_length: '\S{1,120}'  # Регулярное выражение